### ISSUE TITLE
Could not write request, no suitable HttpMessageConverter grails-2.5.1 with grails-mailgun 2.x

### ISSUE THREAD

**Issue by NelsonWu419** [orkonano/grails-mailgun#17]
mailgun{
    apiKey = 'key-43534435435'
    domain = '32342342.mailgun.org'

```
message{
    defaultFrom = 'service@t.com'
    defaultTo = 't@tttt.com'
    defaultSubject = 'BigHamlet tiene promociones para vos'
    format = 'html'
    defaulTemplate = '/mailTemplate/test'
    defaultReplyTo = 'service@ttttt.com'
}
```

}

no suitable HttpMessageConverter found for request type [groovy.util.ConfigObject]

ERROR GrailsExceptionResolver:213  - HttpMessageNotWritableException occurred when processing request: [GET] /cmd/testMail
Could not write request: no suitable HttpMessageConverter found for request type [groovy.util.ConfigObject]. Stacktrace follows:
org.springframework.http.converter.HttpMessageNotWritableException: Could not write request: no suitable HttpMessageConverter found for request type [groovy.util.ConfigObject]
    at org.springframework.http.converter.FormHttpMessageConverter.writePart(FormHttpMessageConverter.java:336)
    at org.springframework.http.converter.FormHttpMessageConverter.writeParts(FormHttpMessageConverter.java:311)
    at org.springframework.http.converter.FormHttpMessageConverter.writeMultipart(FormHttpMessageConverter.java:301)
    at org.springframework.http.converter.FormHttpMessageConverter.write(FormHttpMessageConverter.java:240)
    at org.springframework.http.converter.FormHttpMessageConverter.write(FormHttpMessageConverter.java:87)
    at org.springframework.web.client.RestTemplate$HttpEntityRequestCallback.doWithRequest(RestTemplate.java:774)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:567)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:538)
    at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:457)
    at grails.plugins.rest.client.RestBuilder.invokeRestTemplate(RestBuilder.groovy:312)
    at grails.plugins.rest.client.RestBuilder.doRequestInternal(RestBuilder.groovy:273)
    at grails.plugins.rest.client.RestBuilder.doRequestInternal(RestBuilder.groovy:261)
    at grails.plugins.rest.client.RestBuilder.post(RestBuilder.groovy:147)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1432)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:190)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
    at grails.plugin.mailgun.MailgunService.sendMessage(MailgunService.groovy:49)

**Comment by orkonano** [comment]
@NelsonWu419 could you please add more context examples? 

Grails version?

How do you call MailgunService.sendMessage?

**Comment by NelsonWu419** [comment]
grails 2.5.1
yes ,I dall the MailgunService.sendMessage. 

the exception is below

org.springframework.http.converter.HttpMessageNotWritableException: Could not write request: no suitable HttpMessageConverter found for request type [groovy.util.ConfigObject]

**Comment by orkonano** [comment]
@NelsonWu419 i'llegar investigate the issue.
I'm using the plugin in my App without problem
